[project]
name = "select-view-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=2.3.3",
    "streamlit>=1.52.2",
]

[dependency-groups]
dev = [
    "ruff>=0.14.10",
]
